# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arcs/policy/v1/policy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'arcs/policy/v1/policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61rcs/policy/v1/policy.proto\x12\x0e\x61rcs.policy.v1\"P\n\x0fSuggestedAction\x12\r\n\x05retry\x18\x01 \x01(\x05\x12\x1a\n\x12\x62\x61\x63koff_multiplier\x18\x02 \x01(\x01\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x01\"\xa0\x01\n\rDecideRequest\x12\r\n\x05route\x18\x01 \x01(\t\x12\x12\n\nerror_rate\x18\x02 \x01(\x01\x12\x37\n\tsuggested\x18\x03 \x01(\x0b\x32\x1f.arcs.policy.v1.SuggestedActionH\x00\x88\x01\x01\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12\x13\n\x0bobservation\x18\x05 \x03(\x02\x42\x0c\n\n_suggested\"\x80\x01\n\x0e\x44\x65\x63ideResponse\x12\r\n\x05retry\x18\x01 \x01(\x05\x12\x1a\n\x12\x62\x61\x63koff_multiplier\x18\x02 \x01(\x01\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x01\x12\x18\n\x10override_reasons\x18\x04 \x03(\t\x12\x15\n\rfrozen_active\x18\x05 \x01(\x08\x32Q\n\x06Policy\x12G\n\x06\x44\x65\x63ide\x12\x1d.arcs.policy.v1.DecideRequest\x1a\x1e.arcs.policy.v1.DecideResponseB)Z\'github.com/arcs/arcs/policy/v1;policyv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arcs.policy.v1.policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/arcs/arcs/policy/v1;policyv1'
  _globals['_SUGGESTEDACTION']._serialized_start=47
  _globals['_SUGGESTEDACTION']._serialized_end=127
  _globals['_DECIDEREQUEST']._serialized_start=130
  _globals['_DECIDEREQUEST']._serialized_end=290
  _globals['_DECIDERESPONSE']._serialized_start=293
  _globals['_DECIDERESPONSE']._serialized_end=421
  _globals['_POLICY']._serialized_start=423
  _globals['_POLICY']._serialized_end=504
# @@protoc_insertion_point(module_scope)
