apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arcs.fullname" . }}-arcs-config
  labels:
    {{- include "arcs.labels" . | nindent 4 }}
data:
  arcs.default.yaml: |-
{{ .Files.Get "files/arcs.default.yaml" | nindent 4 }}
