{{- if .Values.envoy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arcs.fullname" . }}-envoy
  labels:
    {{- include "arcs.envoyLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: arcs-envoy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "arcs.envoyLabels" . | nindent 8 }}
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          args: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
          ports:
            - containerPort: 10000
              name: http
            - containerPort: 9901
              name: admin
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
      volumes:
        - name: envoy-config
          configMap:
            name: {{ include "arcs.fullname" . }}-envoy
{{- end }}
