apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arcs.fullname" . }}-toxiproxy
  labels:
    {{- include "arcs.toxiproxyLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.toxiproxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: arcs-toxiproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "arcs.toxiproxyLabels" . | nindent 8 }}
    spec:
      containers:
        - name: toxiproxy
          image: "{{ .Values.toxiproxy.image.repository }}:{{ .Values.toxiproxy.image.tag }}"
          imagePullPolicy: {{ .Values.toxiproxy.image.pullPolicy }}
          ports:
            - containerPort: 8474
              name: api
            - containerPort: 8666
              name: echo-proxy
            - containerPort: 8667
              name: cpu-proxy
          resources:
            {{- toYaml .Values.toxiproxy.resources | nindent 12 }}
