apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcs.fullname" . }}-otel-collector
  labels:
    {{- include "arcs.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: otlp-grpc
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      name: otlp-http
    - port: 8889
      targetPort: prom-exp
      name: prom-exp
    - port: 13133
      targetPort: health
      name: health
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: otel-collector
